# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TianWen' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  # 添加 Alamofire 库（示例）
  pod 'Alamofire', '~> 5.6' 
  # 添加 SnapKit（自动布局库）
  pod 'SnapKit'
  # Pods for TianWen
  pod 'FMDB'

  pod 'SwiftyJSON', '~> 5.0'

end
